#!/bin/sh
#Rscript -e "rmarkdown::render('doc.Rmd','html_document')"
#Rscript -e "rmarkdown::render('index.Rmd','pdf_document')"
Rscript -e "rmarkdown::render('index.Rmd','bookdown::gitbook', output_file='docs/index.html', output_dir='docs')"
touch docs/.nojekyll

